-- ============================================================
-- Seed data para PosWeb (MySQL)
-- Ejecutar después de: dotnet ef database update
-- ============================================================

-- Suscripcion (requiere ID_USUARIO=1 admin)
INSERT INTO SUSCRIPCION (ID_SUSCRIPCION, ID_USUARIO_TITULAR, NIVEL, ESTADO, COSTO_MENSUAL, MAX_SUCURSALES, MAX_ADMIN, MAX_USUARIOS, FECHA_INICIO)
SELECT 1, 1, 'Premium', 'Activa', 0, 10, 5, 50, NOW()
WHERE NOT EXISTS (SELECT 1 FROM SUSCRIPCION WHERE ID_SUSCRIPCION = 1);

-- Empresa
INSERT INTO EMPRESA (ID_EMPRESA, NOMBRE, DOCUMENTO, ID_SUSCRIPCION)
SELECT 1, 'Mi Empresa', '30-12345678-9', 1
WHERE NOT EXISTS (SELECT 1 FROM EMPRESA WHERE ID_EMPRESA = 1);

-- Sucursal
INSERT INTO SUCURSAL (ID_SUCURSAL, COD_SUCURSAL, DESC_SUCURSAL, ID_EMPRESA, ACTIVO)
SELECT 1, 'PRINCIPAL', 'Sucursal Principal', 1, TRUE
WHERE NOT EXISTS (SELECT 1 FROM SUCURSAL WHERE ID_SUCURSAL = 1);

-- Actualizar admin
UPDATE USUARIO SET
    ID_SUCURSAL_DEFAULT = 1,
    SUSCRIPCION_ACTIVA = TRUE
WHERE ID_USUARIO = 1;
