// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PosWeb.Data;

#nullable disable

namespace PosWeb.Migrations
{
    [DbContext(typeof(PosDbContext))]
    [Migration("20260224014359_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("PosWeb.Domain.Producto", b =>
                {
                    b.Property<int>("ID_PRODUCTO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_PRODUCTO");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ACTIVO");

                    b.Property<string>("CODIGO_BARRA")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("CODIGO_BARRA");

                    b.Property<decimal>("COSTO")
                        .HasColumnType("TEXT")
                        .HasColumnName("COSTO");

                    b.Property<string>("NOMBRE")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("NOMBRE");

                    b.Property<decimal>("PRECIO")
                        .HasColumnType("TEXT")
                        .HasColumnName("PRECIO");

                    b.Property<int>("STOCK")
                        .HasColumnType("INTEGER")
                        .HasColumnName("STOCK");

                    b.HasKey("ID_PRODUCTO");

                    b.HasIndex("CODIGO_BARRA");

                    b.HasIndex("NOMBRE");

                    b.ToTable("PRODUCTOS", (string)null);
                });

            modelBuilder.Entity("PosWeb.Domain.RenglonVenta", b =>
                {
                    b.Property<int>("ID_RENGLON_VENTA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_RENGLON_VENTA");

                    b.Property<int>("CANTIDAD")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CANTIDAD");

                    b.Property<int>("ID_PRODUCTO")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_PRODUCTO");

                    b.Property<int?>("ID_VENTA")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PRECIO_UNITARIO")
                        .HasColumnType("TEXT")
                        .HasColumnName("PRECIO_UNITARIO");

                    b.Property<decimal>("SUBTOTAL")
                        .HasColumnType("TEXT")
                        .HasColumnName("SUBTOTAL");

                    b.HasKey("ID_RENGLON_VENTA");

                    b.HasIndex("ID_VENTA");

                    b.ToTable("RENGLONES_VENTA", (string)null);
                });

            modelBuilder.Entity("PosWeb.Domain.Sucursal", b =>
                {
                    b.Property<int>("ID_SUCURSAL")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_SUCURSAL");

                    b.Property<bool>("ACTIVO")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ACTIVO");

                    b.Property<string>("CODIGO")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("CODIGO");

                    b.Property<string>("NOMBRE")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("NOMBRE");

                    b.Property<int>("NUMERO")
                        .HasColumnType("INTEGER")
                        .HasColumnName("NUMERO");

                    b.HasKey("ID_SUCURSAL");

                    b.ToTable("SUCURSALES", (string)null);
                });

            modelBuilder.Entity("PosWeb.Domain.Venta", b =>
                {
                    b.Property<int>("ID_VENTA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_VENTA");

                    b.Property<DateTime>("FECHA")
                        .HasColumnType("TEXT")
                        .HasColumnName("FECHA");

                    b.Property<int>("ID_SUCURSAL")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_SUCURSAL");

                    b.Property<decimal>("TOTAL")
                        .HasColumnType("TEXT")
                        .HasColumnName("TOTAL");

                    b.HasKey("ID_VENTA");

                    b.HasIndex("ID_SUCURSAL");

                    b.ToTable("VENTAS", (string)null);
                });

            modelBuilder.Entity("PosWeb.Domain.RenglonVenta", b =>
                {
                    b.HasOne("PosWeb.Domain.Venta", null)
                        .WithMany("RENGLONES")
                        .HasForeignKey("ID_VENTA");
                });

            modelBuilder.Entity("PosWeb.Domain.Venta", b =>
                {
                    b.HasOne("PosWeb.Domain.Sucursal", null)
                        .WithMany()
                        .HasForeignKey("ID_SUCURSAL")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PosWeb.Domain.Venta", b =>
                {
                    b.Navigation("RENGLONES");
                });
#pragma warning restore 612, 618
        }
    }
}
